- type: npcFaction
  id: Zerg
  hostile:
  - NanoTrasen
  - Syndicate
  - Xeno
  - Dragon
  - ZergNT

- type: npcFaction
  id: ZergNT
  hostile:
  - SimpleHostile
  - Syndicate
  - Xeno
  - Dragon
  - Zerg

- type: accent
  id: zerg
  words:
    - accent-words-xeno-1
    - accent-words-xeno-2
    - accent-words-xeno-3
    - accent-words-xeno-4

- type: entity
  id: MobZerg
  #parent: SimpleSpaceMobBase
  name: Зерг
  suffix: ""
  description: Гремущая длань Роя.
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: InteractionOutline
  - type: RadiationReceiver
  - type: LagCompensation
  - type: MovedByPressure
  - type: HeatResistance
  - type: StandingState
  - type: Polymorphable
  - type: AtmosExposed
  - type: StatusIcon
  - type: Appearance
  - type: InputMover
  - type: Flashable
  - type: Internals
  - type: Clickable
  - type: MobMover
  - type: Climbing
  - type: Examiner
  - type: Pullable
  - type: Actions
  - type: DoAfter
  - type: Alerts
  - type: Buckle

  - type: Input
    context: "human"
  - type: MovementSpeedModifier
    baseWalkSpeed : 4
    baseSprintSpeed : 4
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Physics
    bodyType: KinematicController
  - type: Bloodstream
    bloodMaxVolume: 200
    bloodlossDamage:
      types:
        Bloodloss:
          1
    bloodlossHealDamage:
      types:
        Bloodloss:
          -1
  - type: Damageable
    damageContainer: Biological
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage:
      types:
        Heat: 1
  - type: Temperature
    heatDamageThreshold: 360
    coldDamageThreshold: -150
    currentTemperature: 310
    coldDamage:
      types:
        Cold : 0.1
    specificHeat: 42
    heatDamage:
      types:
        Heat : 0.1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibBehavior { }
  - type: StatusEffects
    allowed:
    - SlowedDown
    - Stutter
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Pacified
  - type: Body
    prototype: Animal
  - type: InjectableSolution
    solution: chemicals
  - type: RotationVisuals
    defaultRotation: 0
    horizontalRotation: 0
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning
  - type: NameIdentifier
    group: GenericNumber
  - type: SlowOnDamage
    speedModifierThresholds:
      60: 0.7
      80: 0.5
  - type: MobPrice
    price: 1500 # Living critters are valuable in space.

  - type: HTN
    rootTask:
      task: XenoCompound
    blackboard:
      NavClimb: !type:Bool
        true
      NavInteract: !type:Bool
        true
      NavPry: !type:Bool
        true
      NavSmash: !type:Bool
        true
  - type: NpcFactionMember
    factions:
    - Zerg
  - type: Tool
    speed: 0.8
    qualities:
      - Prying
    useSound:
      path: /Audio/_CraftStation/Zergs/zerg_pry.ogg
  - type: Reactive
    groups:
      Flammable: [Touch]
      Extinguish: [Touch]
  - type: Hands
  - type: Sprite
    noRot: true
    drawdepth: Mobs
    sprite: _CraftStation/Mobs/Aliens/Zergs/ling.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: running
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.3
        density: 1000
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: MobState
  - type: MobThresholds
    thresholds:
      0: Alive
      150: Critical
      200: Dead
  - type: Grammar
    attributes:
      proper: true
      gender: epicene
  - type: Stamina
    excess: 200
  - type: DamageStateVisuals
    rotate: true
    states:
      Alive:
        Base: stand
      Critical:
        Base: crit
      Dead:
        Base: dead
  - type: Puller
  - type: Butcherable
    butcheringType: Spike
    spawned:
    - id: FoodMeatXeno
      amount: 6
  - type: TypingIndicator
    proto: alien
  - type: Tag
    tags:
      - CannotSuicide
      - DoorBumpOpener
      - FootstepSound
  - type: Perishable
    molsPerSecondPerUnitMass: 0.0005